### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by Shayan-To** [cyanomiko/dcnnt-py#12]
Please add Windows support.

**Comment by Probotious** [comment]
Does this not work for windows? i downloaded Device Connect and I cant figure out how to install the server in win10.

**Comment by sameerasw** [comment]
> Does this not work for windows? i downloaded Device Connect and I cant figure out how to install the server in win10.

same... I would love to have some instructions :)

**Comment by tbone2k-git** [comment]
The installation seems to work on Windows, somehow.
But the actual service does not work, it's not meant to be run on Windows it seems?

```
>d:\bin\dev\python_v3.12_64bit\Scripts\dcnnt.exe pair
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "d:\bin\dev\python_v3.12_64bit\Scripts\dcnnt.exe\__main__.py", line 4, in <module>
  File "D:\bin\dev\python_v3.12_64bit\Lib\site-packages\dcnnt\dcnnt.py", line 6, in <module>
    from .app import DConnectApp
  File "D:\bin\dev\python_v3.12_64bit\Lib\site-packages\dcnnt\app.py", line 13, in <module>
    from .device_manager import DeviceManager, Device
  File "D:\bin\dev\python_v3.12_64bit\Lib\site-packages\dcnnt\device_manager.py", line 5, in <module>
    from .common import derive_key
  File "D:\bin\dev\python_v3.12_64bit\Lib\site-packages\dcnnt\common\__init__.py", line 5, in <module>
    from .jsonconf import *
  File "D:\bin\dev\python_v3.12_64bit\Lib\site-packages\dcnnt\common\jsonconf.py", line 7, in <module>
    class ConfEntryBase:
  File "D:\bin\dev\python_v3.12_64bit\Lib\site-packages\dcnnt\common\jsonconf.py", line 9, in ConfEntryBase
    HOME_DIR = os.environ['HOME']
               ~~~~~~~~~~^^^^^^^^
  File "<frozen os>", line 685, in __getitem__
KeyError: 'HOME'
```
So I run this to "fake" the missing HOME env variable on Windows (by creating it).. 
`>set HOME=%USERPROFILE%`
But after that I get..

`>d:\bin\dev\python_v3.12_64bit\Scripts\dcnnt.exe pair
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "d:\bin\dev\python_v3.12_64bit\Scripts\dcnnt.exe\__main__.py", line 7, in <module>
  File "D:\bin\dev\python_v3.12_64bit\Lib\site-packages\dcnnt\dcnnt.py", line 31, in main
    app = DConnectApp(args.configuration_directory, False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\bin\dev\python_v3.12_64bit\Lib\site-packages\dcnnt\app.py", line 46, in __init__
    self.environment = self.init_environment()
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\bin\dev\python_v3.12_64bit\Lib\site-packages\dcnnt\app.py", line 84, in init_environment
    xdg_runtime_dir = env.get('XDG_RUNTIME_DIR', os.path.join('/', 'var', 'run', 'user', str(os.getuid())))
                                                                                             ^^^^^^^^^
AttributeError: module 'os' has no attribute 'getuid'. Did you mean: 'getpid'?`

Seems like a module difference between Linux and Windows?!..

If that script is meant to display notification for Linux desktops, I guess it won't do anything on Windows anyway, right?

**Comment by denini08** [comment]
Hi! I was browsing through the project issues and noticed this one about Windows compatibility.

I went ahead and created this fix to help out. 

Happy to contribute to the project!

Let me know if you need any changes or have feedback on the approach.
