### ISSUE TITLE
KeyError: 'HOME'

### ISSUE THREAD

**Issue by lord85** [cyanomiko/dcnnt-py#16]
PS C:\Windows\system32> dcnnt pair
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\lord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\dcnnt.exe\__main__.py", line 4, in <module>
  File "C:\Users\lord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\dcnnt\dcnnt.py", line 6, in <module>
    from .app import DConnectApp
  File "C:\Users\lord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\dcnnt\app.py", line 13, in <module>
    from .device_manager import DeviceManager, Device
  File "C:\Users\lord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\dcnnt\device_manager.py", line 5, in <module>
    from .common import derive_key
  File "C:\Users\lord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\dcnnt\common\__init__.py", line 5, in <module>
    from .jsonconf import *
  File "C:\Users\lord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\dcnnt\common\jsonconf.py", line 7, in <module>
    class ConfEntryBase:
  File "C:\Users\lord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\dcnnt\common\jsonconf.py", line 9, in ConfEntryBase
    HOME_DIR = os.environ['HOME']
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'

**Comment by cyanomiko** [comment]
Sorry, Windows is not supported now.
