### ISSUE TITLE
none of the commands run

### ISSUE THREAD

**Issue by ovvabc123** [cyanomiko/dcnnt-py#24]
none of the commands work

I get this error:
C:\Windows\System32>dcnnt pair
Traceback (most recent call last):
   File "<frozen runpy>", line 198, in _run_module_as_main
   File "<frozen runpy>", line 88, in _run_code
   File "C:\Python311\Scripts\dcnnt.exe\__main__.py", line 4, in <module>
   File "C:\Python311\Lib\site-packages\dcnnt\dcnnt.py", line 6, in <module>
     from .app import DConnectApp
   File "C:\Python311\Lib\site-packages\dcnnt\app.py", line 13, in <module>
     from .device_manager import DeviceManager, Device
   File "C:\Python311\Lib\site-packages\dcnnt\device_manager.py", line 5, in <module>
     from .common import derive_key
   File "C:\Python311\Lib\site-packages\dcnnt\common\__init__.py", line 5, in <module>
     from .jsonconf import *
   File "C:\Python311\Lib\site-packages\dcnnt\common\jsonconf.py", line 7, in <module>
     class ConfEntryBase:
   File "C:\Python311\Lib\site-packages\dcnnt\common\jsonconf.py", line 9, in ConfEntryBase
     HOME_DIR = os.environ['HOME']
                ~~~~~~~~~~^^^^^^^^
   File "<frozen os>", line 679, in __getitem__
KeyError: 'HOME'

I really don't know what to do with this.
every time I run a command, it throws this. (translated with google translate)

**Comment by cyanomiko** [comment]
Sorry, Windows is not supported. Maybe later...
