### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by omgwtfbbqpls** [cyanomiko/dcnnt-py#5]
I'm using Windows 7, Python 3.6, and pip-20.1.1. When I type `dcnnt start` I get this mystical scroll of arcane shite:

```
C:\Windows\system32>dcnnt start
Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_mai
n
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\Scripts\dcnnt.exe\__main__.py", line 4, in <mo
dule>
  File "c:\program files\python36\lib\site-packages\dcnnt\dcnnt.py", line 6, in
<module>
    from .app import DConnectApp
  File "c:\program files\python36\lib\site-packages\dcnnt\app.py", line 13, in <
module>
    from .device_manager import DeviceManager, Device
  File "c:\program files\python36\lib\site-packages\dcnnt\device_manager.py", li
ne 5, in <module>
    from .common import derive_key
  File "c:\program files\python36\lib\site-packages\dcnnt\common\__init__.py", l
ine 5, in <module>
    from .jsonconf import *
  File "c:\program files\python36\lib\site-packages\dcnnt\common\jsonconf.py", l
ine 7, in <module>
    class ConfEntryBase:
  File "c:\program files\python36\lib\site-packages\dcnnt\common\jsonconf.py", l
ine 9, in ConfEntryBase
    HOME_DIR = os.environ['HOME']
  File "c:\program files\python36\lib\os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'
```

I just want a lightweight, secure way to control foobar2000 and MPC-HC from my phone. Hopefully this app can do that, once I fix whatever this is.

Edit: Apparently KDE Connect now supports Windows and can sort of do those things, but it has its' share of problems. Hopefully this project gains traction too.

**Comment by cyanomiko** [comment]
Sorry, Windows is not supported. Maybe WSL on Win10 be useful for launching dcnnnt.
