### ISSUE TITLE
Installation Error Windows

### ISSUE THREAD

**Issue by LIME-S** [cyanomiko/dcnnt-py#6]
when i try to install the program with pip i get the following error message:

Collecting dcnnt
  Using cached dcnnt-0.3.6-py3-none-any.whl (22 kB)
Collecting pycryptodome>=3.9.3
  Using cached pycryptodome-3.9.8.tar.gz (15.6 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\bin\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Emil\\AppData\\Local\\Temp\\pip-install-8u2rtl29\\pycryptodome\\setup.py'"'"'; __file__='"'"'C:\\Users\\Emil\\AppData\\Local\\Temp\\pip-install-8u2rtl29\\pycryptodome\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Emil\AppData\Local\Temp\pip-pip-egg-info-etvkq3_d'
         cwd: C:\Users\Emil\AppData\Local\Temp\pip-install-8u2rtl29\pycryptodome\
    Complete output (20 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Emil\AppData\Local\Temp\pip-install-8u2rtl29\pycryptodome\setup.py", line 457, in <module>
        set_compiler_options(package_root, ext_modules)
      File "C:\Users\Emil\AppData\Local\Temp\pip-install-8u2rtl29\pycryptodome\compiler_opt.py", line 341, in set_compiler_options
        clang = compiler_is_clang()
      File "C:\Users\Emil\AppData\Local\Temp\pip-install-8u2rtl29\pycryptodome\compiler_opt.py", line 251, in compiler_is_clang
        return test_compilation(source, msg="clang")
      File "C:\Users\Emil\AppData\Local\Temp\pip-install-8u2rtl29\pycryptodome\compiler_opt.py", line 82, in test_compilation
        objects = compiler.compile([fname], extra_postargs=extra_cc_options)
      File "c:\bin\python\python39\lib\distutils\_msvccompiler.py", line 323, in compile
        self.initialize()
      File "c:\bin\python\python39\lib\distutils\_msvccompiler.py", line 220, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\bin\python\python39\lib\site-packages\setuptools\msvc.py", line 314, in msvc14_get_vc_env
        return _msvc14_get_vc_env(plat_spec)
      File "c:\bin\python\python39\lib\site-packages\setuptools\msvc.py", line 268, in _msvc14_get_vc_env
        raise distutils.errors.DistutilsPlatformError(
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    Testing support for clang
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output

**Comment by cyanomiko** [comment]
Sorry, Windows is not currently supported.

**Comment by theAkito** [comment]
@cyanomiko 

Will Windows ever be supported?
